### ISSUE TITLE
default values for pointer fields are unsupported

### ISSUE THREAD

**Issue by dwrensha** [capnproto/capnpc-rust#38]
Currently capnpc-rust ignores default values for struct and list fields, treating them as if they had no default.

**Comment by alubbe** [comment]
Could you elaborate a little bit on a) why and b) what that means?
Specifically, I get these warnings
```
warning: [UNSUPPORTED] Ignoring default value "" for text field foo. 
warning: [UNSUPPORTED] Ignoring non-null default for list field bar. 
```
for these fields
```
  foo @1:  Text = "";
  bar @2: List(UInt32) = [];
```

**Comment by dwrensha** [comment]
Ah, good point. We probably shouldn't be emitting a warning when an explicit default matches whatever the implicit default would be.

These field definitions, with explicit defaults:
```capnp
  foo @1: Text = "";
  bar @2: List(UInt32) = [];
```

have the same meaning as these definitions with implicit defaults:

```capnp
  foo @1: Text;
  bar @2: List(UInt32);
```

In general, every field always has a default. The implicit default for a primitive field is zero. The implicit default for a list field is the empty list, and the implicit default for a struct field has a zeroed data section and an all-null pointer section.

For pointer fields, you can distinguish between "default" and "null" by using a `has_foo()` accessor. If you call `get_foo()` on a null pointer, you'll get the default value.

**Comment by dwrensha** [comment]
I've somewhat improved the situation here: https://github.com/dwrensha/capnpc-rust/commit/421674174c599cc4a7d246006678468586d12f37

Unfortunately, it's not trivial to detect when the warning should be suppressed in the `List` and `Struct` cases.

**Comment by dwrensha** [comment]
> Could you elaborate a little bit on a) why

The warning is to make sure you're aware that pointer defaults are currently unimplemented in capnpc-rust.

Of course, the long-term solution here is to actually implement pointer defaults. I think doing so should be fairly straightforward, but I haven't done it yet because I haven't needed to.

**Comment by dwrensha** [comment]
Fixed in: https://github.com/capnproto/capnproto-rust/commit/f9ae25c977662b64b0724f465f34cacab8747b86
